import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import CodeEditor from "../components/CodeEditor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const defaultCode = `
  // write your algo
  `
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <div className="flex gap-2  justify-center my-8 mx-22">
            <div className="flex-1 border p-5">
              {/* use markdown */}
              Cho một chuỗi chỉ gồm các dấu ngoặc (), { }, [], hãy kiểm tra xem chuỗi đó có đóng mở đúng thứ tự không.
            </div>
            <CodeEditor defaultCode={defaultCode} />
          </div>
        </main>
      </div>
    </>
  );
}
